version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: legionmc/mcgreggor.net:base-image
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:3000"
    networks:
      - webnet
networks:
  webnet:
